### PR TITLE
[WIP] clustering refactor

### PR DESCRIPTION
**Pull request by colehurwitz**
separating cluster_chunk from ensembling

### CODE REVIEW

**Comment by colehurwitz** [comment]
Will add some tests. thoughts on the structure @cwindolf ?

**Comment by cwindolf** [comment]
could even run the cluster_chunk loop in parallel if we want

**Comment by colehurwitz** [comment]
@julienboussard

**Comment by julienboussard** [comment]
@colehurwitz @cwindolf looks good to me!

**Pull request merged**
